[lint]
select = ["A", "ARG", "C", "E", "F", "I", "TC"]
ignore = ["C901", "E701", "E501"]

[lint.isort]
lines-after-imports = 1
sections = {"dublib" = ["dublib"], "melon" = ["melon"]}
section-order = [
	"future",
	"standard-library",
	"third-party",
	"dublib",
	"melon",
	"first-party",
	"local-folder"
]
