name: Ruff

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install 3.14

      - name: Fetch shared Ruff config
        run: curl -sSfo ruff.toml https://raw.githubusercontent.com/otaku-melons/.github/refs/heads/main/ruff.toml

      - name: Run Ruff
        run: uvx ruff check .
        